### PR TITLE
Modifying "test" mode to support batches

### PR DESCRIPTION
**Pull request by lematt1991**
This substantially improves testing throughput.

### CODE REVIEW

**Comment by amdegroot** [comment]
Hi I'm sorry I have not gotten around to merging this. Will look at it when I get home from vacation in the next couple days as I do not have my laptop with me currently. Thanks for making this pull request!

**Comment by Cadene** [comment]
It works well! Thank you @ml9951

**Comment by amdegroot** [comment]
Sorry this is so late but closing as I just updated myself since nn.Softmax now accepts dim arg. Thanks for the PR and for pointing these things out.

**Comment by JappaB** [comment]
@Cadene, could you share your adjustments for the calculations of the mAP?

**Pull request closed without merging**
